### ISSUE TITLE
Proposal - bringing indent in line with mix format?

### ISSUE THREAD

**Issue by gasparch** [elixir-editors/vim-elixir#383] opened 2017-11-02 12:33 UTC
Elixir 1.6 is coming and it will bring with it `mix format` and a lot of pain. 

Indenting code with `vim-elixir` after it was formatted with `mix format` causes non-consistent look.

For example `mix format` thinks this code should look like

```
defmodule Sample do
  def test(
        arg1,
        arg2,
        arg3
      ) do
    {:match, val1, val2} = arg1
  end
end
```

Selecting and indenting it in `vim-elixir` causes this: 
```
defmodule Sample do
  def test(
    arg1,
    arg2,
    arg3
  ) do
    {:match, val1, val2} = arg1
  end
end
```

I would really happy to avoid any infighting between these two tools and have them produce exactly same code. 

Having `mix format` actually may allow automated testing of indent functionality, because we can take any code base and make sure that `vim-elixir` and `mix format` produce exactly same output.  

So, what do you think, should I start some PR with fixes?

**Comment by jbodah** [comment] 2017-11-02 19:34
This is a dupe of https://github.com/elixir-editors/vim-elixir/issues/376 but there is more info here so I will close the other. I started working on some of these locally. I've built some automation for pulling elixir core and checking against it and have been fixing issues one by one.

The changes introduced by `mix format` also let us greatly simplify some aspects of `vim-elixir` and let us retire some old non-performant rules so I want to make sure we tackle some of those. I also want to make sure that we don't introduce regressions and retire old tests that no longer make sense

It would be great to break down the work needed into finer grain tasks that can be worked on in parallel.

I'd like to push up my changes before going wild on tasks as there are some higher level pain points I'd like to make sure get addressed. If you have any ideas as to how we should identify and break up tasks then I'd be interested in hearing about them

**Comment by gasparch** [comment] 2017-11-03 08:43
Does it make sense to outsource all work for indenting to Elixir's function https://hexdocs.pm/elixir/master/Code.html#format_string!/2  ?

And have something like ElixirSense that will server as a gateway to Elixir process making all decisions about indentation? While it adds external dependency - it is possible to make all indentation code aware of source file's AST and make correct decisions every time. Without trying to parse Elixir code in vim script :) 

I would totally like this for indenting regions, because on large pieces of code (over 100 lines) it works really slow now (3-4 sec) and mix format is definitely faster for a whole file (<1sec) even with VM startup time. If we keep it running - it will be even faster.

**Comment by jbodah** [comment] 2017-11-03 13:22
> Does it make sense to outsource all work for indenting to Elixir's function https://hexdocs.pm/elixir/master/Code.html#format_string!/2 ?

I'm open to this idea however I think in the long term we want to have rules in place to proactively indent instead of relying on an external program. Here's some reasons why I don't want to rely on this long-term:

* having a BEAM process adds another place for things to go wrong
* the indent function gets called a whole lot and the overhead will almost certainly be noticeable
* should the BEAM bootup be noticeable we have two options: 1) block and do things synchronously (slow, disruptive), or 2) find some way to do things asynchronously (potential data loss if buffer changes before command returns)

In addition, most of the bottlenecks in vim-elixir are due to:

* complex block indent rules that don't need to be supported and could be simplified (like the one you mentioned above)
* checking if we are in a string/comment (I don't think we can do better than we are with this without building out a full AST ourselves unfortunately)

With that said though, I think this is definitely worth trying out. Would you be interested in spiking on shelling out to an Elixir process? I believe [alchemist.vim](https://github.com/slashmili/alchemist.vim) might do something like this (running a background server and communicating with it on-demand)

**Comment by mhinz** [comment] 2017-11-03 15:21
FWIW, I just released a small plugin that integrates the formatter into Vim: https://github.com/mhinz/vim-mix-format.

Feedback welcome. :]

**Comment by gasparch** [comment] 2017-11-03 18:27
Yes, idea was exactly to implement functionality in a way like alchemist.vim does.

It also opens way to have another type of highlighting ( watch 1 minute of this https://youtu.be/dkZFtimgAcM?t=15m58s BTW the whole talk is hillarious, but this one minute is relevant, [here is JS plugin that implements is](https://github.com/bigfish/vim-js-context-coloring) ).


I'll look into it - and possibly overtaking over ElixirSense to implement not only auto-completion, but also formatting/etc functions - we don't want two beam processes running :)

**Comment by jbodah** [comment] 2018-01-24 15:26
Closing due to #396 . I would still like to see the indent rules get fixed up to match `mix format` and I think the best way to do that is on a case-by-case basis with lots and lots of unit tests

**Closed by jbodah** 2018-01-24 15:26 UTC
Labels: discussion, enhancement, epic
